from pathlib import Path
p=Path('/mnt/data/uc_e2ee/uc_work')
# global theme assets
(p/'static/theme.css').write_text('''html[data-theme="dark"] body{background:#0b1220!important;color:#e5e7eb!important}html[data-theme="dark"] .nav,html[data-theme="dark"] .top,html[data-theme="dark"] .card,html[data-theme="dark"] .header,html[data-theme="dark"] .composer,html[data-theme="dark"] .actions-panel,html[data-theme="dark"] .messages,html[data-theme="dark"] .cv,html[data-theme="dark"] section{background:#111827!important;color:#e5e7eb!important;border-color:#263244!important}html[data-theme="dark"] input,html[data-theme="dark"] textarea,html[data-theme="dark"] select{background:#0f172a!important;color:#e5e7eb!important;border-color:#334155!important}html[data-theme="dark"] a{color:#7db2ff!important}html[data-theme="dark"] .muted,html[data-theme="dark"] .sub{color:#94a3b8!important}.uc-theme-toggle{position:fixed;right:14px;bottom:14px;z-index:9999;border:0;border-radius:999px;padding:10px 13px;font-weight:800;cursor:pointer;background:#1456c4;color:#fff;box-shadow:0 6px 20px #0003}.uc-appearance-link{font-weight:800;text-decoration:none}''')
(p/'static/theme.js').write_text('''(()=>{const stored=localStorage.getItem('uc_theme')||'system';function apply(t){const v=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t;document.documentElement.dataset.theme=v}apply(stored);window.addEventListener('storage',e=>{if(e.key==='uc_theme')apply(e.newValue||'system')});window.ucSetTheme=t=>{localStorage.setItem('uc_theme',t);apply(t)}})();''')
(p/'templates/appearance_settings.html').write_text('''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Appearance</title><link rel="stylesheet" href="{{ url_for('static',filename='theme.css') }}"><script src="{{ url_for('static',filename='theme.js') }}"></script><style>body{font-family:system-ui;background:#f3f6fa;margin:0;color:#172033}.wrap{max-width:720px;margin:30px auto;padding:0 14px}.card{background:#fff;border-radius:16px;padding:22px;box-shadow:0 5px 25px #0001}.choices{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.choice{padding:20px;border:2px solid #e5e7eb;border-radius:14px;cursor:pointer}.choice input{margin-right:7px}@media(max-width:600px){.choices{grid-template-columns:1fr}}</style></head><body>{% include 'return_nav.html' %}<main class="wrap"><div class="card"><h1>🎨 Appearance</h1><p>Choose the normal, dark or system theme. This preference is stored locally in your browser.</p><div class="choices"><label class="choice"><input type="radio" name="theme" value="light">☀️ Light</label><label class="choice"><input type="radio" name="theme" value="dark">🌙 Dark</label><label class="choice"><input type="radio" name="theme" value="system">🖥 System</label></div><p><a href="{{ url_for('user_home') }}">← Back to home</a></p></div></main><script>const saved=localStorage.getItem('uc_theme')||'system';document.querySelectorAll('[name=theme]').forEach(x=>{x.checked=x.value===saved;x.onchange=()=>ucSetTheme(x.value)});</script>{% include 'mobile_nav.html' %}</body></html>''')
# inject theme assets into all HTML files
for f in p.glob('templates/*.html'):
    s=f.read_text()
    if 'static/theme.css' not in s:
        s=s.replace('</head>','<link rel="stylesheet" href="{{ url_for(\'static\', filename=\'theme.css\') }}"><script src="{{ url_for(\'static\', filename=\'theme.js\') }}"></script></head>',1)
    if 'uc-theme-toggle' not in s and '<body' in s:
        s=s.replace('</body>','<button class="uc-theme-toggle" type="button" onclick="ucSetTheme((localStorage.getItem(\'uc_theme\')||\'system\')===\'dark\'?\'light\':\'dark\')" title="Toggle dark/light theme">🌓</button></body>',1)
    f.write_text(s)
# modify chat: add controls and call area
f=p/'templates/chat.html'; s=f.read_text()
anchor='<div class="header-actions">'
if 'id="chatSettingsBtn"' not in s:
    s=s.replace(anchor,anchor+'<a class="btn" href="{{ url_for(\'detailed_profile\', user_id=other_user[\'id\']) }}">👤 Profile</a><button class="btn" id="chatSettingsBtn" type="button">🎨 Chat Theme</button>',1)
# insert settings panel before messages
needle='<div class="messages" id="messageBox">'
panel='''<div id="chatSettings" style="display:none;background:var(--chat-panel,#fff);padding:14px;border-radius:14px;margin:10px 0"><b>Inbox appearance</b><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:8px"><select id="chatTheme"><option value="default">Default</option><option value="light">Light</option><option value="dark">Dark</option><option value="midnight">Midnight</option><option value="forest">Forest</option></select><select id="chatWallpaper"><option value="none">No wallpaper</option><option value="dots">Dots</option><option value="gradient">Gradient</option><option value="paper">Paper</option><option value="night">Night</option></select><select id="disappear"><option value="0">Disappearing: Off</option><option value="30">30 seconds</option><option value="300">5 minutes</option><option value="3600">1 hour</option><option value="86400">24 hours</option></select><button class="btn primary" id="saveChatPref">Save</button></div><div style="margin-top:8px;font-size:12px;color:#667085">Wallpaper and theme are private to your inbox view. Disappearing messages are deleted from the server after the selected period; recipients may still screenshot or copy them.</div><div style="margin-top:8px"><button class="btn" id="safetyBtn" type="button">🔢 Show safety number</button><button class="btn" id="backupBtn" type="button">🔐 Backup keys</button><button class="btn" id="restoreBtn" type="button">♻️ Restore keys</button></div><div id="safetyOut" style="margin-top:8px;font-family:monospace"></div></div>'''
s=s.replace(needle,panel+needle,1)
# add JS before </script> final
extra=r'''
// Chat appearance
const prefURL='/api/chat/{{ other_user["id"] }}/preferences';
const chatPanel=document.getElementById('chatSettings');
document.getElementById('chatSettingsBtn').onclick=()=>chatPanel.style.display=chatPanel.style.display==='none'?'block':'none';
function applyChatTheme(p){const b=document.getElementById('messageBox');b.dataset.chatTheme=p.theme;b.style.background=p.wallpaper==='dots'?'radial-gradient(#bbb 1px,transparent 1px) 0 0/14px 14px':p.wallpaper==='gradient'?'linear-gradient(135deg,#dbeafe,#fce7f3)':p.wallpaper==='paper'?'repeating-linear-gradient(0deg,#fafafa,#fafafa 27px,#f0f0f0 28px)':'p.wallpaper==='night'?'linear-gradient(135deg,#020617,#172554)':'';if(p.theme==='dark'||p.theme==='midnight'){b.style.color='#e5e7eb';b.style.backgroundColor='#111827'}if(p.theme==='forest'){b.style.backgroundColor='#e8f5e9'}}
fetch(prefURL).then(r=>r.json()).then(p=>{document.getElementById('chatTheme').value=p.theme;document.getElementById('chatWallpaper').value=p.wallpaper;document.getElementById('disappear').value=String(p.disappearing_seconds||0);applyChatTheme(p)});
document.getElementById('saveChatPref').onclick=async()=>{const data={theme:document.getElementById('chatTheme').value,wallpaper:document.getElementById('chatWallpaper').value,disappearing_seconds:Number(document.getElementById('disappear').value)};const r=await fetch(prefURL,{method:'POST',headers:{'Content-Type':'application/json','X-CSRFToken':CSRF},body:JSON.stringify(data)});if(r.ok){applyChatTheme(data);alert('Chat appearance saved.')}else alert('Could not save chat settings.')};
// Safety number / encrypted backup recovery. Backup is encrypted in the browser with a password; the server only stores ciphertext.
document.getElementById('safetyBtn').onclick=async()=>{const r=await fetch('/api/e2ee/safety-number/'+OTHER_USER_ID);const d=await r.json();document.getElementById('safetyOut').textContent=r.ok?'Safety number: '+d.safety_number:'Keys are not ready on both devices.'};
async function backupKeys(){const pass=prompt('Create a backup password (never send this password to the server):');if(!pass)return;const raw=localStorage.getItem(keyStorage);if(!raw)return alert('No local encryption key exists on this device.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const base=await crypto.subtle.importKey('raw',encoder.encode(pass),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(raw));const r=await fetch('/api/e2ee/backup',{method:'POST',headers:{'Content-Type':'application/json','X-CSRFToken':CSRF},body:JSON.stringify({salt:b64(salt),iv:b64(iv),ciphertext:b64(ct)})});alert(r.ok?'Encrypted key backup saved.':'Backup failed.')}
async function restoreKeys(){const r=await fetch('/api/e2ee/backup');const d=await r.json();if(!d.ciphertext)return alert('No encrypted backup found.');const pass=prompt('Enter your backup password:');if(!pass)return;try{const base=await crypto.subtle.importKey('raw',encoder.encode(pass),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:unb64(d.salt),iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']);const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(d.iv)},key,unb64(d.ciphertext));localStorage.setItem(keyStorage,decoder.decode(raw));alert('Keys restored. Reloading…');location.reload()}catch(e){alert('Wrong password or corrupted backup.')}}
document.getElementById('backupBtn').onclick=backupKeys;document.getElementById('restoreBtn').onclick=restoreKeys;
