import {useState} from "react";
import {Alert,Image,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {commentPost,likePost} from "../api";
import type {Post} from "../types";
import {MediaCard} from "./MediaCard";
export function PostCard({post,onChange}:{post:Post;onChange:(p:Post)=>void}){const[comment,setComment]=useState("");const[busy,setBusy]=useState(false);
async function toggle(){if(busy)return;setBusy(true);try{const r=await likePost(post.id);onChange({...post,liked_by_me:r.liked,like_count:r.like_count});}catch(e){Alert.alert("Could not react",e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
async function sendComment(){const value=comment.trim();if(!value)return;try{const r=await commentPost(post.id,value);setComment("");onChange({...post,comment_count:r.comment_count,comments:[...post.comments,{name:"You",comment:value,created_at:new Date().toISOString()}].slice(-3)});}catch(e){Alert.alert("Comment failed",e instanceof Error?e.message:"Please try again.");}}
return <View style={styles.card}><View style={styles.head}>{post.photo_url?<Image source={{uri:post.photo_url}} style={styles.avatar}/>:<View style={styles.avatar}/>}<View style={{flex:1}}><Text style={styles.name}>{post.name}</Text><Text style={styles.meta}>@{post.username} · {post.created_at}</Text></View><Text style={styles.kind}>{post.post_type==="reel"?"REEL":"POST"}</Text></View>{post.caption?<Text style={styles.caption}>{post.caption}</Text>:null}<MediaCard uri={post.media_url} type={post.media_type}/><View style={styles.actions}><Pressable onPress={toggle} style={styles.action}><Text style={post.liked_by_me?styles.active:styles.actionText}>♥ {post.like_count}</Text></Pressable><Text style={styles.commentCount}>Comments {post.comment_count}</Text></View>{post.comments.length>0?<View style={styles.comments}>{post.comments.map((c,i)=><Text key={c.created_at+"-"+i} style={styles.comment}><Text style={styles.commentName}>{c.name}: </Text>{c.comment}</Text>)}</View>:null}<View style={styles.commentBox}><TextInput value={comment} onChangeText={setComment} placeholder="Write a comment…" placeholderTextColor="#98A2B3" style={styles.input} maxLength={1000}/><Pressable onPress={sendComment} style={styles.send}><Text style={styles.sendText}>Send</Text></Pressable></View></View>;}
const styles=StyleSheet.create({card:{backgroundColor:"#fff",borderRadius:20,padding:14,marginBottom:14,gap:10},head:{flexDirection:"row",alignItems:"center",gap:10},avatar:{width:44,height:44,borderRadius:22,backgroundColor:"#EAECF0"},name:{fontSize:16,fontWeight:"800",color:"#101828"},meta:{color:"#667085",marginTop:2,fontSize:12},kind:{fontSize:11,fontWeight:"900",color:"#175CD3"},caption:{fontSize:15,color:"#344054",lineHeight:21},actions:{flexDirection:"row",alignItems:"center",gap:18},action:{paddingVertical:6},actionText:{fontWeight:"800",color:"#475467"},active:{fontWeight:"900",color:"#D92D20"},commentCount:{color:"#667085",fontWeight:"700"},comments:{gap:5},comment:{color:"#475467",lineHeight:18},commentName:{fontWeight:"800",color:"#101828"},commentBox:{flexDirection:"row",alignItems:"center",gap:8},input:{flex:1,borderWidth:1,borderColor:"#D0D5DD",borderRadius:12,paddingHorizontal:12,paddingVertical:9,color:"#101828"},send:{backgroundColor:"#175CD3",paddingHorizontal:14,paddingVertical:10,borderRadius:12},sendText:{color:"#fff",fontWeight:"800"}});
