import {useCallback,useEffect,useState} from "react";
import {ActivityIndicator,Alert,FlatList,Image,Modal,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from "react-native";
import {Link,useRouter} from "expo-router";
import {getFeed,getNotifications,getReels,getStories} from "../../src/api";
import type {Post,Story} from "../../src/types";
import {PostCard} from "../../src/components/PostCard";
import {MediaCard} from "../../src/components/MediaCard";
import {useAuth} from "../../src/context/AuthContext";
export default function HomeScreen(){const{user}=useAuth();const router=useRouter();const[posts,setPosts]=useState<Post[]>([]);const[reels,setReels]=useState<Post[]>([]);const[stories,setStories]=useState<Story[]>([]);const[selected,setSelected]=useState<Story|null>(null);const[refreshing,setRefreshing]=useState(false);const[unread,setUnread]=useState(0);
const load=useCallback(async()=>{const[a,b,c,d]=await Promise.all([getFeed(),getReels(),getStories(),getNotifications()]);setPosts(a.posts);setReels(b.posts);setStories(c.stories);setUnread(d.notifications.filter(x=>String(x.is_read||"0")==="0").length);},[]);
useEffect(()=>{load().catch(e=>Alert.alert("Feed error",e instanceof Error?e.message:"Please try again."));},[load]);
const header=<View style={s.header}><View style={s.top}><View style={{flex:1}}><Text style={s.title}>Good day, {user?.name?.split(" ")[0]||"there"}</Text><Text style={s.sub}>Social + study + work in one place.</Text></View><Pressable onPress={()=>router.push("/notifications")} style={s.bell}><Text>🔔</Text>{unread>0?<View style={s.badge}><Text style={s.badgeText}>{unread>9?"9+":unread}</Text></View>:null}</Pressable></View><View style={s.sectionHead}><Text style={s.section}>Stories</Text><Text style={s.muted}>{stories.length}</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{stories.map(x=><Pressable key={x.id} onPress={()=>setSelected(x)} style={s.story}>{x.photo_url?<Image source={{uri:x.photo_url}} style={s.storyAvatar}/>:<View style={s.storyAvatar}/>}<Text numberOfLines={1} style={s.storyLabel}>{x.is_mine?"Your story":x.name}</Text></Pressable>)}</ScrollView><View style={s.sectionHead}><Text style={s.section}>Reels</Text><Link href="/reels" style={s.link}>View all</Link></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{reels.slice(0,5).map(x=><View key={x.id} style={s.reel}><MediaCard uri={x.media_url} type={x.media_type} height={190}/><Text numberOfLines={2} style={s.reelText}>{x.caption||x.name}</Text></View>)}{reels.length===0?<Text style={s.muted}>No Reels yet.</Text>:null}</ScrollView><Text style={[s.section,{marginTop:12}]}>Feed</Text></View>;
return <><FlatList style={s.page} contentContainerStyle={s.list} data={posts} keyExtractor={x=>String(x.id)} renderItem={({item})=><PostCard post={item} onChange={next=>setPosts(cur=>cur.map(x=>x.id===next.id?next:x))}/>} ListHeaderComponent={header} ListEmptyComponent={<Text style={s.muted}>No posts yet. Be the first to share.</Text>} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);try{await load();}catch(e){Alert.alert("Refresh failed",e instanceof Error?e.message:"Please try again.");}finally{setRefreshing(false);}}}/>}/><Modal visible={Boolean(selected)} transparent animationType="fade" onRequestClose={()=>setSelected(null)}><View style={s.modal}><View style={s.box}><Pressable onPress={()=>setSelected(null)} style={s.close}><Text style={s.closeText}>Close</Text></Pressable>{selected?<MediaCard uri={selected.media_url} type={selected.media_type} height={480}/>:null}<Text style={s.storyName}>{selected?.name}</Text>{selected?.caption?<Text style={s.storyCaption}>{selected.caption}</Text>:null}</View></View></Modal></>;}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#F2F4F7"},list:{padding:12,paddingBottom:30},header:{gap:9,marginBottom:5},top:{flexDirection:"row",alignItems:"center",gap:10,paddingVertical:7},title:{fontSize:25,fontWeight:"900",color:"#101828"},sub:{color:"#667085",marginTop:3},bell:{backgroundColor:"#fff",width:44,height:44,borderRadius:22,alignItems:"center",justifyContent:"center"},badge:{position:"absolute",right:-1,top:-2,minWidth:18,height:18,borderRadius:9,backgroundColor:"#D92D20",alignItems:"center",justifyContent:"center"},badgeText:{color:"#fff",fontSize:10,fontWeight:"900"},sectionHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:7},section:{fontSize:18,fontWeight:"900",color:"#101828"},muted:{color:"#667085"},link:{color:"#175CD3",fontWeight:"800"},row:{gap:10,paddingVertical:7},story:{width:72,alignItems:"center",gap:5},storyAvatar:{width:62,height:62,borderRadius:31,borderWidth:2,borderColor:"#175CD3",backgroundColor:"#EAECF0"},storyLabel:{fontSize:11,color:"#344054",maxWidth:72,textAlign:"center"},reel:{width:185,backgroundColor:"#fff",borderRadius:16,padding:7,gap:6},reelText:{fontSize:12,color:"#344054",fontWeight:"700"},modal:{flex:1,backgroundColor:"rgba(0,0,0,.78)",justifyContent:"center",padding:14},box:{backgroundColor:"#111827",borderRadius:22,padding:10,gap:10},close:{alignSelf:"flex-end",padding:6},closeText:{color:"#fff",fontWeight:"800"},storyName:{color:"#fff",fontSize:18,fontWeight:"900"},storyCaption:{color:"#E4E7EC"}});
